export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';

export const IS_POST_SELECTED = 'IS_POST_SELECTED';
export const FETCH_SELECTED_POST_SUCCESS = 'FETCH_SELECTED_POST_SUCCESS';
export const FETCH_SELECTED_POST_FAIL = 'FETCH_SELECTED_POST_FAIL';

export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_FAIL = 'ADD_NEW_POST_FAIL';
export const INITIALISE_POST_SUBMITTED = 'INITIALISE_POST_SUBMITTED';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';



